autoinstall_wait    = "<wait2m>"
ubuntu_version_slug = "2204"
box_name            = "ubuntu2204-arm"
box_version         = "1.0.0"
box_version_desc    = "initial release"
box_org             = "wesdemos/"
ubuntu_iso_url      = "https://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.1-live-server-arm64.iso"
ubuntu_iso_checksum = "file:https://cdimage.ubuntu.com/releases/22.04.1/release/SHA256SUMS"